### ISSUE TITLE
Create shipping label API cannot fill "Critical Incident ID"

### ISSUE THREAD

**Issue by hatasum** [microsoft/devices-hardware-dev-center-manager#9]
We have to fill Incident ID when we're creating a shipping label to follow MDA requirement if needed, but we can't achieve this due to there has no API related. 
Does MSFT help us to get that API or have any method to achieve it? Thanks!

**Comment by Ben-Carpenter** [comment]
@hatasum, could you please explain what you are looking for a bit more.

**Comment by Ben-Carpenter** [comment]
Closing this issue, if you are still experiencing an issue please reopen.
